Webshop/config/routes.rb
Rails.application.routes.draw do

  get 'address/form'

  resources :users, :sessions, :shoes, :categories
  resources :addresses
  resources :charges
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/' => 'shoes#index'
  post '/shoes/:id' => 'order_items#create'

  root to: 'shoes#index'

end

Webshop/app/models/address.rb
class Address < ApplicationRecord
    has_and_belongs_to_many :purchases
    has_and_belongs_to_many :people
    belongs_to :city
    belongs_to :addressType
end

Webshop/app/models/address_type.rb
class AddressType < ApplicationRecord
    has_many :addresses, dependent: :destroy
end

Webshop/app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

Webshop/app/models/category.rb
class Category < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

Webshop/app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    has_many :addresses, dependent: :destroy
end

Webshop/app/models/color.rb
class Color < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

Webshop/app/models/country.rb
class Country < ApplicationRecord
    has_many :cities, dependent: :destroy
end

Webshop/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :user
  has_many :order_items

  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

Webshop/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :shoe
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :size, presence: true

  before_save :finalize

  def price
    if persisted?
      self[:price]
    else
      shoe.price
    end
  end

private

  def finalize
    self[:price] = price
  end
end

Webshop/app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders, dependent: :destroy
end

Webshop/app/models/person.rb
class Person < ApplicationRecord
    has_and_belongs_to_many :addresses
end

Webshop/app/models/role.rb
class Role < ApplicationRecord
    has_many :users, dependent: :destroy
end

Webshop/app/models/shoe.rb
class Shoe < ApplicationRecord
    belongs_to :style
    belongs_to :brand
    belongs_to :color
    belongs_to :category
    has_and_belongs_to_many :shoe_sizes
    has_many :cart_shoe_details, dependent: :destroy
    has_many :carts, through: :cart_shoe_details
end

Webshop/app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
    has_and_belongs_to_many :shoes

end

Webshop/app/models/style.rb
class Style < ApplicationRecord
    has_many :shoes, dependent: :destroy
end

Webshop/app/models/user.rb
class User < ApplicationRecord
    belongs_to :role
    has_many :orders, dependent: :destroy

    has_secure_password

    before_create { generate_token(:auth_token) }

    def generate_token(column)
        begin
          self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    #validates :email, presence: true, length: { maximum: 255 },
    #                  format: { with: VALID_EMAIL_REGEX }
    
    #validates :password, presence: true, length: { minimum: 8, message: "Password must be at least 8 characters long" }
end

Webshop/app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

    before_action :authorize, only: [:addToCart]

    def index
        @shoes = Shoe.all
    end

    def show 
        @shoe = Shoe.find(params[:id])
        @style = Style.find(@shoe.style_id);
        @shoes = @style.shoes;
    end

    def addToCart
        if params[:buy]
            redirect_to '/cart'
        else
            redirect_to action: :show
        end
    end
end

Webshop/app/helpers/carts_helper.rb
module CartsHelper
end

Webshop/app/helpers/charges_helper.rb
module ChargesHelper
end

Webshop/app/helpers/orders_helper.rb
module OrdersHelper
end

Webshop/app/helpers/sessions_helper.rb
module SessionsHelper
end

Webshop/app/helpers/shoes_helper.rb
module ShoesHelper
end

Webshop/app/helpers/users_helper.rb
module UsersHelper
end

Webshop/app/views/shoes/_filter.html.erb
<div>
    FILTER
    <%= form_tag do %>
        Brend: <br>
        <%= select_tag "brand" %>
        <br>
        Velicina: <br>
        <%= select_tag "size" %>
        <br>
        Boja: <br>
        <%= select_tag "color" %>
        <br>
        Stil: <br>
        <%= select_tag "style" %>
        <br>
        Cijena: <br>
        <%= select_tag "price_range" %>
        <br>
    <% end %>
</div>

Webshop/app/views/shoes/_shoesTable.html.erb
<table id="shoeTable">
    <% @shoes.find_in_batches(batch_size: 4) do |shoe_batch| %>
        <tr>
        <% shoe_batch.each do |shoe| %>
            <td>
                <div id="shoeData">
                    <%= link_to image_tag(shoe.photo_url, size: "135x135"), shoe_path(shoe), id: "photoImg" %>
                </div>
            </td>
        <% end %>
        <tr>
    <% end %>
</table>

Webshop/app/views/shoes/_showForm.html.erb
<div class="container">
    <div class="row">
        <%= form_for OrderItem.new, url: {controller: "order_items", action: "create"}, class: "form-inline" do |f|%>

            <table id="shoe-form-table">
                <tr>
                    <td class="shoe-form-col-1">
                        Size
                    </td>
                    <td class="shoe-form-col-2">
                        Quantity
                    </td>
                </tr>
                <tr>
                    <td class="shoe-form-col-1">         
                        <%= f.select :size,  options_from_collection_for_select(@shoe.shoe_sizes.order(:size), "size", "size"), 
                            {:prompt => "All sizes"}, {id:"shoe-form-select", class: "form-control"} %>
                    </td>
                    <td class="shoe-form-col-2">
                        <%= f.number_field :quantity, value: "1", id: "shoe-form-text-field", 
                        class: "form-control", min: 1 %> 
                         <%= f.hidden_field :shoe_id, value: @shoe.id %>
                    </td>
                </tr>
            </table>
            <div id="shoe-form-row-btn">
                <div id="shoe-form-row-btn-left">
                    <%= f.submit "ADD TO CART", id: "formButtonAdd", class: "btn btn-success" %>
                </div>
                <div id="shoe-form-row-btn-right">
                    <%= f.submit "BUY NOW", name: "buy", id: "formButtonBuy", class: "btn btn-success" %> 
                </div>
            </div>
        <% end %>
    </div>
</div>

Webshop/app/views/shoes/index.html.erb
<div class="container" id="index-page">
    <div class="row">
        <img src="http://www.4usky.com/data/out/83/164744921-shoes-wallpapers.jpg" 
            width="100%" height="350px">
    </div>
    <div class="row">
        <div class="col-xs-2 col-xs-offset-5">
            <div id="brand_select">
                Featured Products <br>
                <%= select("brand", "brand_id", Brand.all.collect {|b| [ b.brand, b.id ] }) %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <%= render partial: "shoesTable", locals: {brandSearch: 1, styleSearch: nil} %>
        </div>
    </div>
</div>

Webshop/app/views/shoes/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-4 col-xs-offset-2">
            <img src= <%= @shoe.photo_url %> width="300" height="300">
        </div>
        <div class="col-xs-4">
            <div class="row">
                <p id="shoe-title">
                    <%= @shoe.model %>
                </p>
                <p id="shoe-description">
                    <%= @shoe.description %>
                </p>
            </div>
            <div class="row" id="shoe-form-div">
                <%= render "showForm" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2" id="shoe-similar">
            <p> Similar products </p>
            <%= render partial: "shoesTable", locals: {brandSearch: nil, styleSearch: @shoe.style_id} %>
        </div>
    </div>
</div>